version: "3.8"
services:

  mongodb:
    image: mongo
    ports:
      - "27017-27019:27017-27019"
    restart: always
    networks:
      - mongonet

  mongo-proxy:
    build: .
    image: mongo-proxy:1.0
    ports:
      - "8080:8080"
    environment:
      #- GIN_MODE=release
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      #- MONGODB_USER=username
      #- MONGODB_PASS=password
    restart: always
    networks:
      - mongonet
    depends_on:
      - mongodb

  mongo-proxy-swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8082:8080"
    environment:
      - BASE_URL=/swagger
      - SWAGGER_JSON=/mnt/swagger.json
    volumes:
      - ./swagger.json:/mnt/swagger.json
    restart: always
    networks:
      - mongonet
    depends_on:
      - mongodb
      - mongo-proxy

networks:
  mongonet:
